# checking whether all GDCs are generically depending on something
#There is probably a conceptual mistake here, since this should be axioms and not direct connections between classes
# lv 6


PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT ?GDC (CONCAT("Warning: Generically Dependent Entity ", STR(?label), " doesn't generically depend on some entity.") AS ?warningMessage)
WHERE {
    #get all the subclasses of GDC
    ?GDC rdfs:subClassOf+ obo:BFO_0000031 .
    ?GDC rdfs:label ?label .

    # check whether it doesn't generically depend on something
    FILTER NOT EXISTS {
        ?GDC obo:BFO_0000084 ?y .
    }
}
